# Generated by Django 4.1.7 on 2023-11-27 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('1', 'Limpio'), ('2', 'Sucio')], max_length=1)),
                ('tipo', models.CharField(choices=[('1', 'Individual'), ('2', 'Doble')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('1', 'Disponible'), ('2', 'Ocupado')], max_length=1)),
                ('bateria', models.IntegerField()),
                ('mapa', models.TextField()),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.plataforma')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitio.habitacion')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.plataforma'),
        ),
        migrations.CreateModel(
            name='EstacionDeCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
                ('robots', models.ManyToManyField(to='sitio.robot')),
            ],
        ),
    ]
